post_install()
{
	echo -n "Suppressing ALSA drivers... "
	/usr/lib/oss/scripts/remove_drv.sh
	depmod -a
	/usr/sbin/chkconfig --add rc.oss
	echo "done."
	true
}

post_upgrade()
{
	post_install
	true
}

pre_remove()
{
	echo -n "Restoring ALSA drivers... "
	/usr/lib/oss/scripts/restore_drv.sh
	echo "done."
	/usr/sbin/chkconfig --del rc.oss
	true
}

post_remove()
{
	depmod -a
	true
}

op=$1
shift
$op $*
