# arg 1:  the new package version
post_install() {
  sbin/ldconfig -r . &>/dev/null
  usr/sbin/groupadd -g 21 slocate &>/dev/null
}

# arg 1:  the new package version
# arg 2:  the old package version
post_upgrade() {
  echo "WARNING slocate: You need to run updatedb because 2.x and 3.x db not compatible!"
  /bin/true
}

# arg 1:  the old package version
pre_remove() {
  usr/sbin/groupdel slocate &>/dev/null
}

op=$1
shift

$op $*
