post_install() {
	echo -n "updating gdk loaders... "
	if [ -f /usr/bin/gdk-pixbuf-query-loaders ]
	then
		/usr/bin/gdk-pixbuf-query-loaders > /etc/gtk-2.0/gdk-pixbuf.loaders
		/usr/bin/gdk-pixbuf-query-loaders --update-cache
	fi
	if [ -f /usr/bin/gdk-pixbuf-query-loaders-3.0 ]
	then
		/usr/bin/gdk-pixbuf-query-loaders-3.0 --update-cache
	fi
	echo "done."
}

post_upgrade() {
	post_install $1
}

op=$1
shift

$op $*
