post_install() {
	echo -n "updating gdk loaders... "
	/usr/bin/gdk-pixbuf-query-loaders > /etc/gtk-2.0/gdk-pixbuf.loaders
	/usr/bin/gdk-pixbuf-query-loaders --update-cache
	echo "done."
}

post_upgrade() {
	post_install $1
}

post_remove() {
	echo -n "updating gdk loaders... "
	/usr/bin/gdk-pixbuf-query-loaders > /etc/gtk-2.0/gdk-pixbuf.loaders
	/usr/bin/gdk-pixbuf-query-loaders --update-cache
	echo "done."
}

op=$1
shift

$op $*
