# arg 1:  the new package version
post_install() {
	echo -n "updating font cache... "
	/sbin/ldconfig -r .
	/usr/bin/fc-cache
	echo "done."
	chkconfig --add rc.xprint
}

# arg 1:  the new package version
# arg 2:  the old package version
post_upgrade() {
	post_install $1
}

# arg 1:  the old package version
pre_remove() {
	/bin/true
}

# arg 1:  the old package version
post_remove() {
	chkconfig --del rc.splash
}


op=$1
shift

$op $*

# vim: ft=sh
