post_install() {
	echo -n "generating the top-level Info node... "
	mkinfodir /usr/share/info > /usr/share/info/dir 2> /dev/null
	echo "done."
}

post_upgrade() {
	echo -n "generating the top-level Info node... "
	mkinfodir /usr/share/info > /usr/share/info/dir 2> /dev/null
	echo "done."
}

post_remove() {
	echo -n "generating the top-level Info node... "
	mkinfodir /usr/share/info > /usr/share/info/dir 2> /dev/null
	echo "done."
}

op=$1
shift

$op $*
