post_install()
{
	getent group messagebus 2>&1 > /dev/null || groupadd -g 38 messagebus
	getent passwd messagebus 2>&1 > /dev/null || useradd -s /bin/false -c "D-BUS system user" -d '/' -u 38 -g messagebus messagebus
	dbus-uuidgen --ensure 
}

post_upgrade()
{
	post_install
}

post_remove()
{
	getent passwd messagebus 2>&1 > /dev/null && userdel messagebus
	getent group messagebus 2>&1 > /dev/null && groupdel messagebus
}

op=$1
shift
$op $*
