# arg 1:  the new package version
post_install() {
	if ! grep -q '^rsyncd:' /etc/group ; then
		groupadd -g 28 rsyncd
	fi
	if ! grep -q '^rsyncd:' /etc/passwd ; then
                useradd -u 28 -g 28 rsyncd
	fi
}

# arg 1:  the new package version
# arg 2:  the old package version
post_upgrade() {
	post_install $1
}

# arg 1:  the old package version
pre_remove() {
	userdel rsyncd
	groupdel rsyncd
}

op=$1
shift

$op $*

# vim: ft=sh
