# arg 1:  the new package version
post_install() {
  cd /etc/rc.d/rcS.d
  ln -sf ../rc.lvm S14rc.lvm
  chkconfig --add rc.lvm
}

# arg 1:  the new package version
# arg 2:  the old package version
post_upgrade() {
  /bin/true
}

# arg 1:  the old package version
pre_remove() {
  rm /etc/rc.d/rcS.d/S14rc.lvm
  chkconfig --del rc.lvm
}

# arg 1:  the old package version
post_remove() {
  /bin/true
}

op=$1
shift
$op $*
