HS_DIR=/usr/share/haskell/$_F_haskell_register_dir

post_install() {
	echo "Updating ghc-pkg cache"
	/usr/bin/ghc-pkg recache
	echo "Registering package"
	[ -e /usr/bin/ghc-pkg ] && ${HS_DIR}/register.sh
}

pre_remove() {
	echo "Unregistering package"
	[ -e /usr/bin/ghc-pkg ] && ${HS_DIR}/unregister.sh
	echo "Updating ghc-pkg cache"
	/usr/bin/ghc-pkg recache
}

pre_upgrade() {
  pre_remove
}

post_upgrade() {
  post_install
}

op=$1
shift

$op $*
