post_install()
{
	pear install --nodeps -r /var/lib/pear/$_F_pear_name.xml
}

post_upgrade()
{
	# make this a bit more silent since a 1.0-1 -> 1.0-1 upgrade is, but
	# pear does not like such upgrades
	echo -n "updating the pear database... "
	pear upgrade --nodeps -r /var/lib/pear/$_F_pear_name.xml &>/dev/null
	echo "done."
}

pre_remove()
{
	pear uninstall --nodeps -r $_F_pear_name
}

op=$1
shift
$op $*
