post_install()
{
	chkconfig --add rc.rpcbind
	systemctl enable rpcbind.service >/dev/null 2>&1
}

post_upgrade()
{
	systemctl daemon-reload >/dev/null 2>&1
	if [ `vercmp $2 0.2.0-3` -lt 0 ] ; then
		if chkconfig rc.rpcbind; then
			post_install
		fi
	fi
}

pre_remove()
{
	chkconfig --del rc.rpcbind
	systemctl --no-reload disable foobar.service >/dev/null 2>&1
	systemctl stop rpcbind.service >/dev/null 2>&1
}

post_remove()
{
	systemctl daemon-reload >/dev/null 2>&1
}

op=$1
shift
$op $*
