dictlst=/usr/lib/ooo-1.1/share/dict/ooo/dictionary.lst

post_install()
{
	echo "DICT sl SI sl_SI" >>$dictlst
	echo "HYPH sl SI hyph_sl_SI" >>$dictlst
}

post_upgrade()
{
        pre_remove
        post_install
}

pre_remove()
{
	tempfile=`mktemp`
	cat $dictlst |grep -v "\(DICT sl SI sl_SI\|HYPH sl SI hyph_sl_SI\)" >$tempfile
	cat $tempfile >$dictlst
	rm -f $tempfile
}

op=$1
shift
$op $*

# vim: ft=sh
