# arg 1:  the new package version
post_install() {
cat << EOF
  ==> ipcheck successfully installed !
  ==> edit /etc/ipcheck.conf to change the username, password and hostname
  ==> Finally, run ipcheck as root to update your dyndns ip
EOF
}

post_upgrade() {
cat << EOF
  ==> ipcheck successfully installed !
  ==> edit /etc/ipcheck.conf to change the username, password and hostname
  ==> Finally, run ipcheck as root to update your dyndns ip
EOF
}

op=$1
shift
$op $*
