post_install()
{
	systemctl disable getty\@tty1.service > /dev/null 2>&1
	systemctl enable kmscon.service > /dev/null 2>&1
	systemctl daemon-reload > /dev/null 2>&1
}

post_upgrade()
{
	systemctl daemon-reload > /dev/null 2>&1
}

pre_remove()
{
	systemctl --no-reload disable kmscon.service > /dev/null 2>&1
	systemctl stop kmscon.service > /dev/null 2>&1
}

post_remove()
{
	systemctl enable getty\@tty1.service > /dev/null 2>&1
	systemctl daemon-reload > /dev/null 2>&1
}

op=$1
shift
$op $*
