\input texinfo
@setfilename frugalware.info
@settitle Frugalware GNU/Linux official documentation

@copying
	This is the officially relelased manual and documentation, written and 
	maintained by the Frugalware developer team.
	            
	Copyright @copyright{} 2005 Frugalware developer team.
         
	This document is distributed under the
	GNU Free Documentation License (GFDL).
@end copying

@node Top,	First steps, Top, Top
@c node-name,     next,        previous,         up

@center Official documentation for the Frugalware GNU/Linux Distribution (v0.4)

@menu
* First steps::            About, FAQ, history, etc.
* Install and configure::  Installation of the distribution and configuration
                           of the services like printing, networking etc.
* Development::            Making packages, recompiling existing ones with
                           more features than in the distribution.
* Contents::
* Top::
@end menu

@insertcopying

@c proper href: @uref{}
@c command sample: @samp{rm / -rf}
@c
@c
@c
@c the first big section, lead-in
@include frugalware-firststeps.texi

@c configuration
@include frugalware-installconfig.texi

@c developer docs, about recompiling, creating packages
@include frugalware-devel.texi

@node Contents
@unnumbered

@contents

@bye
