post_install() {
        getent group rtkit > /dev/null 2>&1 || /usr/bin/groupadd -g 94 rtkit
        getent passwd rtkit > /dev/null 2>&1 || /usr/bin/useradd -r -c 'rtkit user' -u 94 -g rtkit rtkit
        passwd -l rtkit > /dev/null
}

post_upgrade()
{
	post_install
}

post_remove()
{
        getent passwd rtkit > /dev/null 2>&1 || /usr/bin/userdel -r rtkit
		getent group rtkit > /dev/null 2>&1 || /usr/bin/groupdel rtkit
}


op=$1
shift
$op $*
