post_install() {
  getent group chrony &>/dev/null || groupadd -g 130 chrony >/dev/null
  getent passwd chrony &>/dev/null || useradd -u 130 -g chrony -d /var/lib/chrony -c 'Network Time Protocol' -s /bin/false chrony >/dev/null
}

post_upgrade() {
    getent group chrony &>/dev/null || groupadd -r -g 130 chrony >/dev/null
    getent passwd chrony &>/dev/null || useradd -r -u 130 -g chrony -d /var/lib/chrony -c 'Network Time Protocol' -s /bin/false chrony >/dev/null
    chown -R 130:130 /var/lib/chrony
}