# arg 1:  the new package version
post_install() {
	[ `grep hpaio < /etc/sane.d/dll.conf|wc -l` == 0 ] && \
	echo hpaio >> /etc/sane.d/dll.conf 2> /dev/null
}

# arg 1:  the new package version
# arg 2:  the old package version
post_upgrade() {
	post_install $1
}

# arg 1:  the old package version
pre_remove() {
	sed -i 's|hpaio||g' /etc/sane.d/dll.conf 2> /dev/null
}

op=$1
shift

$op $*

# vim: ft=sh
