# arg 1:  the new package version
pre_install()
{
	if [ `/usr/bin/grep slocate /etc/group |wc -l` != 0 ]; then
		/usr/sbin/groupdel slocate
	fi
}

# arg 1:  the new package version
post_install()
{
	if [ `/usr/bin/grep locate /etc/group |wc -l` == 0 ]; then
		/usr/sbin/groupadd -g 21 locate
	fi
	echo "Creating initial mlocate db (this may take a few minutes)..."
	/etc/cron.daily/updatedb
	echo "Done."
}

op=$1
shift
$op $*
