post_install()
{
	if ! grep -q '^firebird:' /etc/group ; then
		/usr/sbin/groupadd -g 115 firebird
	fi
	if ! grep -q '^firebird:' /etc/passwd ; then
		/usr/sbin/useradd -u 115 -g 115 -s /bin/false -c "Firebird" -d /var/lib/firebird firebird
	fi
}

pre_remove()
{
	/usr/sbin/userdel -r firebird >/dev/null 2>&1
	/usr/sbin/groupdel firebird >/dev/null 2>&1
	rm -fr /var/lib/firebird 2>&1
}

post_upgrade()
{
	post_install
}

op=$1
shift

$op $*
