post_install()
{
	chkconfig --add rc.wicd
	systemctl daemon-reload >/dev/null 2>&1
	systemctl enable wicd.service >/dev/null 2>&1
}

post_upgrade()
{
	systemctl daemon-reload >/dev/null 2>&1
	systemctl try-restart wicd.service >/dev/null 2>&1
}

pre_remove()
{
	systemctl stop wicd.service >/dev/null 2>&1
	systemctl disable wicd.service >/dev/null 2>&1
	chkconfig --del rc.wicd
}

post_remove()
{
	systemctl daemon-reload >/dev/null 2>&1
}

op=$1
shift

$op $*

# vim: ft=sh
