post_install()
{
	if ! grep -q '^munin:' /etc/group ; then
		/usr/bin/groupadd -g 47 munin
	fi
	if ! grep -q '^munin:' /etc/passwd ; then
		/usr/bin/useradd -u 47 -g 47 -s /bin/false -c "Munin User" -d /var/lib/munin munin
	fi
}

post_remove()
{
	if [ ! -f /usr/bin/munin-node ]; then
		/usr/bin/userdel -r munin >/dev/null 2>&1
		/usr/bin/groupdel munin >/dev/null 2>&1
	fi

}

op=$1
shift
$op $*

# vim: ft=sh
