post_install()
{
	if ! [ `grep '/usr/lib/gtkhtml312/lib' etc/ld.so.conf` ]; then
		echo "/usr/lib/gtkhtml312/lib" >>etc/ld.so.conf
		/sbin/ldconfig -r .
	else
		/sbin/ldconfig -r . > /dev/null 2>&1
	fi
}

post_upgrade()
{
        post_install $1
}

post_remove()
{
	cat /etc/ld.so.conf | grep -v '/usr/lib/gtkhtml312/lib' >/tmp/ld.so.conf.new
	mv /tmp/ld.so.conf.new etc/ld.so.conf
	chmod 644 etc/ld.so.conf
        /sbin/ldconfig -r .
}

op=$1
shift
$op $*
