post_install()
{
	/usr/sbin/chkconfig --add rc.quota
	ln -sf '/lib/systemd/system/quotacheck.service' '/etc/systemd/system/local-fs.target.wants/quotacheck.service'
	ln -sf '/lib/systemd/system/quotaon.service' '/etc/systemd/system/local-fs.target.wants/quotaon.service'
}

pre_remove()
{
	rm -f '/etc/systemd/system/local-fs.target.wants/quotacheck.service'
	rm -f '/etc/systemd/system/local-fs.target.wants/quotaon.service'
	/usr/sbin/chkconfig --del rc.quota
}

op=$1
shift
$op $*
