post_install()
{
	if ! grep -q '^amavis:' /etc/group ; then
		groupadd -g 40 amavis
	fi
	if ! grep -q '^amavis:' /etc/passwd ; then
                useradd -u 40 -g 40 -s /bin/false -c "Amavisd-new" -d /var/lib/amavis amavis
	fi
	chown -R amavis.amavis /var/lib/amavis
	chown -R amavis.amavis /var/lock/amavis
}

pre_remove()
{
	chkconfig --del rc.amavisd-new
	userdel -r amavis >/dev/null 2>&1
	groupdel amavis >/dev/null 2>&1
}

post_upgrade()
{
	post_install
}

op=$1
shift
$op $*

# vim: ft=sh
