# arg 1:  the new package version
post_install() {
  cd /etc/rc.d/rcS.d
  ln -sf ../rc.splash S03rc.splash
  chkconfig --add rc.splash
}

# arg 1:  the new package version
# arg 2:  the old package version
post_upgrade() {
  /bin/true
}

# arg 1:  the old package version
pre_remove() {
  /bin/true
}

# arg 1:  the old package version
post_remove() {
  chkconfig --del rc.splash
  rm /etc/rc.d/rcS.d/S03rc.splash
}

op=$1
shift
$op $*
