#install script for kvirc
# $1:  the new package version
post_install()
{
	mv /usr/share/services/irc.protocol \
		/usr/share/services/irc.protocol.kvircsave
	mv /usr/share/services/irc.protocol.kvirc \
		/usr/share/services/irc.protocol
}
	
# $1:  the old package version
post_remove()
{
	mv /usr/share/services/irc.protocol.kvircsave \
		/usr/share/services/irc.protocol
}
				
op=$1
shift
$op $*
			
# vim: ft=sh