pre_install() {
	if [ -d /usr/bin/defaults ]; then
		rm -rf /usr/bin/defaults
	fi
}

post_install() {
#	/usr/lib/thunderbird/thunderbird-rebuild-databases.pl
	export HOME="/root"
	export MOZ_DISABLE_GNOME=1
	thunderbird -register
}

pre_upgrade() {
	pre_install
}

post_upgrade() {
	post_install
}

post_remove() {
	if [ -d /usr/lib/thunderbird ]; then
		rm -rf /usr/lib/thunderbird
	fi
}

op=$1
shift

$op $*
