.TH LINUX32 1 "May 2002" "SuSE Labs" "Linux User's Manual"
.SH NAME 
linux32 \- Set i686 uname emulation processes. 
linux64 \- Reset uname emulation
.SH SYNOPSIS
.B linux32
[
.B \-\-3gb
]
[
.B \-\-4gb
]
command arguments...
.br
.B linux64
command arguments...
.br
.SH DESCRIPTION
.I linux32
changes the personality of command and all its children to 
return 
.I i686
instead of
.I x86_64 
in 
.I uname -a.
This is useful to fool shell scripts or programs that check for the architecture
explicitely into believing that they run on a true 
.I i686
system.
In addition it moves the top of stack of the 32bit child processes to 
.I 0xc0000000.
This is useful to execute some broken applications that break when
the stack top is at 4GB. On the other hand it limits the usable heap
memory more than necessary.
When 
.I --4gb 
is specified this is not done.

.I linux64
resets the uname personality to default.
.SH SEE ALSO
.I uname(1)

.I uname(2) 

.I personality(2)








