post_upgrade()
{
	if [ ! -d var/lib/pacman/local ]; then
		echo -n "converting database... " >&2
		mkdir -p var/lib/pacman/local && \
			usr/bin/convertdb var/lib/pacman/local
		echo "done." >&2
	fi
	if [ `vercmp $2 2.9.5-9` -le -1 ]; then
		echo -n "updating package cache... "
		for i in  `ls /var/cache/pacman/pkg/*.fpm`
		do
			mv $i `dirname $i`/`basename $i .fpm`-i686.fpm
		done
		echo "done."
	fi

	rm -f /.CHANGELOG /.INSTALL
}

op=$1
shift

$op $*

# vim: ft=sh
