# arg 1:  the new package version
post_install() {
  /bin/true
}

# arg 1:  the new package version
# arg 2:  the old package version
post_upgrade() {
  if [ ! -d var/lib/pacman/local ]; then
    echo "==> Converting database..." >&2
    mkdir -p var/lib/pacman/local && usr/bin/convertdb var/lib/pacman/local
    echo "==> Done." >&2
  fi
}

# arg 1:  the old package version
pre_remove() {
  /bin/true
}

op=$1
shift

$op $*
