post_install()
{

	if [ -e /usr/bin/gtk-update-icon-cache ]; then
		gtk-update-icon-cache /usr/share/icons/hicolor/
	fi
}

post_upgrade()
{

	if [ -e /usr/bin/gtk-update-icon-cache ]; then
		gtk-update-icon-cache /usr/share/icons/hicolor/
	fi
}

post_remove()
{

	if [ -e /usr/bin/gtk-update-icon-cache ]; then
		gtk-update-icon-cache /usr/share/icons/hicolor/
	fi
}

op=$1
shift

$op $*

# vim: ft=sh
