post_install()
{
	systemctl enable netconfig.service >/dev/null 2>&1
}

post_upgrade()
{
	systemctl daemon-reload >/dev/null 2>&1
	if [ `vercmp $2 0.9.3-3` -lt 0 ] ; then
		post_install
	fi
}

pre_remove()
{
	systemctl stop netconfig.service >/dev/null 2>&1
	systemctl --no-reload disable netconfig.service >/dev/null 2>&1
}

post_remove()
{
	systemctl daemon-reload >/dev/null 2>&1
}

op=$1
shift
$op $*
