# arg 1:  the new package version
post_install() {
  cd /etc/rc.d/rcS.d
  ln -sf ../rc.fsck S12rc.fsck
  ln -sf ../rc.random S22rc.random
  chkconfig --add rc.random
}

# arg 1:  the new package version
# arg 2:  the old package version
post_upgrade() {
  /bin/true
}

# arg 1:  the old package version
pre_remove() {
  rm /etc/rc.d/rcS.d/S{12rc.fsck,22rc.random}
  chkconfig --del rc.random
}

# arg 1:  the old package version
post_remove() {
  /bin/true
}

op=$1
shift
$op $*
