post_install()
{
	echo -n "updating desktop database..."
	if update-desktop-database > /dev/null 2>&1 ; then
		echo " done."
	else
		echo " failed."
        fi
	

	echo -n "updating hicolor icon cache..."
        if gtk-update-icon-cache -f -t /usr/share/icons/hicolor > /dev/null 2>&1 ; then
		echo " done."
	else
		echo " failed."
        fi
}

post_upgrade()
{
	post_install
}

post_remove()
{
	post_install
}

op=$1
shift

$op $*
