post_install()
{
	if ! grep -q '^distccd:' /etc/group; then
		groupadd -g 104 distccd
	fi
	
	if ! grep -q '^distccd:' /etc/passwd; then
		useradd -u 104 -d /dev/null -g distccd distccd
	fi
	
}

pre_upgrade()
{
	
	if [ -e /sbin/service ]; then
		/sbin/service distccd stop
	fi
}

post_upgrade()
{
	post_install
	if [ -e /sbin/service ]; then
		/sbin/service distccd start
	fi
}

pre_remove()
{
	userdel distccd &> /dev/null
	groupdel distccd &> /dev/null
}

op=$1
shift

$op $*
