# arg 1: the new package version
post_install()
{
	echo -n "updating /etc/shells... "
	sed -i '/\(\/usr\)\/bin\/t\?csh/ d' /etc/shells
	echo -e "/bin/tcsh\n/bin/csh" >> /etc/shells
	echo "done."
}

# arg 1: the new package version
# arg 2: the old package version
post_upgrade()
{
	post_install $1
}

# arg 1: the old package version
pre_remove()
{
	echo -n "updating /etc/shells... "
	sed -i '/\/bin\/t\?csh/ d' /etc/shells
	echo "done."
}

op=$1
shift

$op $*

# vim: ft=sh
