#!/bin/sh
# $Id: ifplugd.action 99 2004-02-08 20:17:59Z lennart $

# This file is part of ifplugd.
#
# ifplugd is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free
# Software Foundation; either version 2 of the License, or (at your
# option) any later version.
#
# ifplugd is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
# for more details.
#
# You should have received a copy of the GNU General Public License
# along with ifplugd; if not, write to the Free Software Foundation,
# Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA.

# Ported to Frugalware Linux by Alex Smith <alex@alex-smith.me.uk>

set -e

if [ -z "$1" ] || [ -z "$2" ] ; then
	logger -s -p local0.err -t ifplugd.action "Wrong arguments"
	exit 1
fi

# Check whether a different profile was given on the kernel command line
profile=$(grep network /proc/cmdline|sed 's/.*network=\([^ ]*\)\( .*\|$\)/\1/')

if [ "$2" = "up" ]; then
	# Bring up the interface
	if [ -z "$profile" ]; then
		exec netconfig start $1
	else
		exec netconfig $profile $1
	fi
elif [ "$2" = "down" ]; then
	exec /sbin/netconfig stop $1
fi

exit 1
