post_install()
{
	if [ -f /usr/share/qt4/mkspecs/qconfig.pri ]; then
		## backup
	  /usr/bin/mv -f /usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/qconfig.pri.backup
 	  /usr/bin/mv -f /usr/share/qt4/mkspecs/qconfig.pri.debug \
		/usr/share/qt4/mkspecs/qconfig.pri
	fi
	if [ -f /usr/share/qt4/mkspecs/features/default_post.prf ]; then
		## backup
	  /usr/bin/mv -f /usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf.backup
	 /usr/bin/mv -f /usr/share/qt4/mkspecs/features/default_post.prf.debug \
		/usr/share/qt4/mkspecs/features/default_post.prf
	fi
}
post_upgrade()
{
	if [ -f /usr/share/qt4/mkspecs/qconfig.pri ]; then
	    /usr/bin/mv -f /usr/share/qt4/mkspecs/qconfig.pri.debug \
			/usr/share/qt4/mkspecs/qconfig.pri
	fi
	if [ -f /usr/share/qt4/mkspecs/features/default_post.prf ]; then
         /usr/bin/mv -f /usr/share/qt4/mkspecs/features/default_post.prf.debug \
                /usr/share/qt4/mkspecs/features/default_post.prf
        fi

}

pre_remove()
{
      if [ -f /usr/share/qt4/mkspecs/qconfig.pri ]; then
          /usr/bin/rm -f /usr/share/qt4/mkspecs/qconfig.pri
          /usr/bin/mv -f /usr/share/qt4/mkspecs/qconfig.pri.backup \
                /usr/share/qt4/mkspecs/qconfig.pri
        fi
	if [ -f /usr/share/qt4/mkspecs/qconfig.pri ]; then
          /usr/bin/rm -f /usr/share/qt4/mkspecs/features/default_post.prf
          /usr/bin/mv -f /usr/share/qt4/mkspecs/features/default_post.prf.backup \
                /usr/share/qt4/mkspecs/features/default_post.prf
        fi
}

op=$1
shift

$op $*

# vim: ft=sh
