post_install()
{
	grep -q proxy /etc/group || groupadd -g 105 proxy
	id proxy &>/dev/null || useradd -u 105 -g proxy -d /var/empty proxy
	chown proxy.proxy var/{cache,log}/squid
}

post_upgrade()
{
	post_install $1
}

pre_remove()
{
	systemctl --no-reload disable squid.service >/dev/null 2>&1
	systemctl stop squid.service >/dev/null 2>&1
	userdel proxy
	groupdel proxy
}

post_remove()
{
	systemctl daemon-reload >/dev/null 2>&1
}

op=$1
shift

$op $*
