post_install() {
	chkconfig --add rc.atd
	systemctl enable atd.service >/dev/null 2>&1
}

post_upgrade() {
	systemctl daemon-reload >/dev/null 2>&1
	if [ `vercmp $2 3.1.13-1` -lt 0 ]; then
		if chkconfig rc.atd; then
			post_install
		fi
	fi
}

pre_remove() {
	chkconfig --del rc.atd
	systemctl --no-reload disable atd.service >/dev/null 2>&1
	systemctl stop atd.service >/dev/null 2>&1
}

post_remove() {
	systemctl daemon-reload >/dev/null 2>&1
}

op=$1
shift
$op $*
