post_install()
{
	sed -i 's/capability/dazuko\ncapability/' /etc/sysconfig/modules
	sed -i 's/dazuko/commoncap\ndazuko/' /etc/sysconfig/modules
	depmod -a
	rmmod capability
	modprobe commoncap
	modprobe dazuko
	modprobe capability
}

post_upgrade()
{
	post_install
}

post_remove()
{
	post_install
}

pre_remove()
{
	sed -i '/^dazuko/d' /etc/sysconfig/modules
	sed -i '/^commoncap/d' /etc/sysconfig/modules
}

op=$1
shift
$op $*
