dictlst=/usr/lib/ooo-1.1/share/dict/ooo/dictionary.lst

post_install()
{
	echo "DICT ru RU ru_RU" >>$dictlst
	echo "HYPH ru RU hyph_ru_RU" >>$dictlst
}

post_upgrade()
{
        pre_remove
        post_install
}

		
pre_remove()
{
	tempfile=`mktemp`
	cat $dictlst |grep -v "\(DICT ru RU ru_RU\|HYPH ru RU hyph_ru_RU\)" >$tempfile
	cat $tempfile >$dictlst
	rm -f $tempfile
}

op=$1
shift
$op $*

# vim: ft=sh
