dictlst=/usr/lib/ooo-1.1/share/dict/ooo/dictionary.lst

post_install()
{
	echo "DICT nl NL nl_NL" >>$dictlst
	echo "HYPH nl NL hyph_nl_NL" >>$dictlst
}

post_upgrade()
{
        pre_remove
        post_install
}
		 
pre_remove()
{
	tempfile=`mktemp`
	cat $dictlst |grep -v "\(DICT nl NL nl_NL\|HYPH nl NL hyph_nl_NL\)" >$tempfile
	cat $tempfile >$dictlst
	rm -f $tempfile
}

op=$1
shift
$op $*

# vim: ft=sh
