post_install() {
        if ! grep -q 'usbmuxd' /etc/group; then
		#create group
		/usr/sbin/groupadd -g 68 usbmuxd 2>/dev/null
		#create user
		/usr/sbin/useradd -s /sbin/nologin -c "usbmuxd user" -d / -u 68 -g usbmuxd usbmuxd 2>/dev/null
        fi

}

post_upgrade()
{
       post_install
}

pre_remove()
{
	/usr/sbin/userdel usbmuxd 2>/dev/null
	/usr/sbin/groupdel usbmuxd 2>/dev/null
	
}

op=$1
shift
$op $*
