post_install()
{
	cd /etc/rc.d/rcS.d
	ln -sf ../rc.splash S03rc.splash
	/usr/sbin/chkconfig --add rc.splash
	/usr/sbin/chkconfig --add rc.zz-splash
}

post_upgrade()
{
	# this can be removed after Frugalware 0.6, it's here to support
	# upgrades since there were no rc.zz-splash in 0.5
	post_install
}

pre_remove()
{
	/usr/sbin/chkconfig --del rc.zz-splash
	/usr/sbin/chkconfig --del rc.splash
	rm /etc/rc.d/rcS.d/S03rc.splash
}

op=$1
shift
$op $*
