
post_install()
{
	echo -e "==> Change your LastFM username and password in /etc/lastfmsubmitd.conf"
	echo -e "==> and the MPD server settings in /etc/lastmp.conf"
	echo -e "==> before starting the LastFM submit daemon. After adding"
	echo -e "==> your username and password, run the following commands:"
	echo -e "==> sudo service lastfmsubmitd start"
	echo -e "==> sudo service lastmp start"
	true
}

post_upgrade()
{
	post_install $*
}

op=$1
shift
$op $*
