post_install() {
	# Fixing an unknown issue, which probably comes from libtar.
	ln -s -f /usr/lib/mono/gac/ICSharpCode.SharpZipLib/0.84.0.0__1b03e6acf1164f73/ICSharpCode.SharpZipLib.dll \
	/usr/lib/mono/1.0/ICSharpCode.SharpZipLib.dll
	if [ -x /usr/sbin/chkconfig ]; then
		chkconfig --add rc.mono
	fi
}

post_upgrade() {
	post_install
}

pre_remove() 
{
	if [ -x /usr/sbin/chkconfig ]; then
		chkconfig --del rc.mono
	fi
}

op=$1
shift

$op $*
