# arg 1:  the new package version
post_install()
{
	if ! [ -x /usr/bin/maildirmake ]; then
	    ln -s /usr/bin/maildirmake.maildrop /usr/bin/maildirmake
	fi
	if ! [ -x /usr/bin/deliverquota ]; then
	    ln -s /usr/bin/deliverquota.maildrop /usr/bin/deliverquota
	fi

}

pre_remove()
{
        if [ -L /usr/bin/maildirmake ]; then
	    rm /usr/bin/maildirmake
	fi
	if [ -L /usr/bin/deliverquota ]; then
	    rm /usr/bin/deliverquota
	fi
}

op=$1
shift

$op $*
