dictlst=/usr/lib/ooo-1.1/share/dict/ooo/dictionary.lst

post_install()
{
	echo "DICT fr FR fr_FR" >>$dictlst
	echo "HYPH fr BE hyph_fr_BE" >>$dictlst
	echo "HYPH fr FR hyph_fr_FR" >>$dictlst
	echo "THES fr FR th_fr_FR" >>$dictlst
}

pre_remove()
{
	tempfile=`mktemp`
	cat $dictlst |grep -v "\(DICT fr FR fr_FR\|HYPH fr BE hyph_fr_BE\|HYPH fr FR hyph_fr_FR\|THES fr FR th_fr_FR\)" >$tempfile
	cat $tempfile >$dictlst
	rm -f $tempfile
}

op=$1
shift
$op $*

# vim: ft=sh
