post_install()
{
	sed 's|"/usr/bin/lxdm"$|"/usr/sbin/lxdm"|' -i /etc/sysconfig/desktop
	sed 's|^#desktop="/usr/sbin/lxdm"$|desktop="/usr/sbin/lxdm"|' -i /etc/sysconfig/desktop
	systemctl enable lxdm@.service
}

post_upgrade()
{
	post_install
}

post_remove()
{
	systemctl delete lxdm@.service
	sed -i 's|^desktop="/usr/sbin/lxdm"$|#desktop="/usr/sbin/lxdm"|' /etc/sysconfig/desktop
}

op=$1
shift

$op $*

# vim: ft=sh
