post_install()
{
	if grep -q /usr/bin/zsh /etc/shells 2> /dev/null ; then
		echo -n "updating /etc/shells... "
		sed -i 's|/usr/bin/zsh|/bin/zsh|' /etc/shells
		echo "done."
	elif ! grep -q /bin/zsh /etc/shells 2> /dev/null ; then
		echo -n "updating /etc/shells... "
		echo "/bin/zsh" >> /etc/shells
		echo "done."
	fi
}

post_upgrade()
{
	post_install $1
}

pre_remove()
{
	echo -n "updating /etc/shells... "
	sed -i '/\/bin\/zsh/ d' /etc/shells
	echo done
}

op=$1
shift

$op $*

# vim: ft=sh
