post_install()
{
	if [  "`grep -v  /usr/bin/zsh /etc/shells`" ]; then
		echo -n "updating /etc/shells... "
		echo "/usr/bin/zsh " >>/etc/shells		
#		sed -i "s|/bin/bzsh|/bin/bzsh\n/usr/bin/zsh|" etc/shells
		echo "done."
	fi
}

post_upgrade()
{
	post_install $1
}

pre_remove()
{
	echo -n "updating /etc/shells... "
	sed -i "s|/usr/bin/zsh||" /etc/shells
	echo done
}

op=$1
shift

$op $*

# set ft=sh
