# arg 1:  the new package version
post_install() {
  groupadd _ntp
  useradd -g _ntp -s /sbin/nologin -d /var/empty -c 'OpenNTP daemon' _ntp
}

# arg 1:  the new package version
# arg 2:  the old package version
post_upgrade() {
  /bin/true
}

# arg 1:  the old package version
pre_remove() {
  userdel _ntp >/dev/null 2>&1
  groupdel _ntp >/dev/null 2>&1
}

# arg 1:  the old package version
post_remove() {
  /bin/true
}

op=$1
shift
$op $*
