# arg 1:  the new package version
post_install()
{
	if ! grep -q '^_ntp:' /etc/group ; then
		groupadd -g 29 _ntp
	fi
	if ! grep -q '^_ntp:' /etc/passwd ; then
                useradd -u 29 -g 29 -s /sbin/nologin -c "OpenNTP daemon" -d /var/empty/ntpd _ntp
	fi
}

# arg 1:  the old package version
pre_remove()
{
	userdel _ntp >/dev/null 2>&1
	groupdel _ntp >/dev/null 2>&1
}

op=$1
shift
$op $*

# vim: ft=sh
