post_install()
{
	/usr/sbin/groupadd amavis
	/usr/sbin/useradd -g amavis -d /var/lib/amavis -s /bin/false \
		-c "Amavisd-new" amavis
	chown -R amavis.amavis /var/lib/amavis
	chown -R amavis.amavis /var/lock/amavis
	echo "Please run 'amavisconf' to configure amavis!"
}

pre_remove()
{
	/usr/sbin/chkconfig --del rc.amavisd-new
	/usr/sbin/userdel -r amavis >/dev/null 2>&1
	/usr/sbin/groupdel amavis >/dev/null 2>&1
}

op=$1
shift
$op $*

# vim: ft=sh
