post_install()
{
	getent group polkitd 2>&1 > /dev/null || groupadd -g 67 polkitd
	getent passwd polkitd 2>&1 > /dev/null || useradd -s /bin/false -c "polkitd" -d '/' -u 67 -g polkitd polkitd
}

post_upgrade()
{
	post_install
}

pre_remove()
{
	systemctl stop polkit.service 2>&1 > /dev/null
}

post_remove()
{
	systemctl daemon-reload 2>&1 > /dev/null
	getent passwd polkitd 2>&1 > /dev/null && userdel polkitd
	getent group polkitd 2>&1 > /dev/null && groupdel polkitd
}

op=$1
shift
$op $*
