# arg 1: the new package version
post_install() {
	echo -n "updating /etc/shells... "
	sed -i '/\(\/usr\)\/bin\/ash/ d' /etc/shells
	echo "/bin/ash" >> /etc/shells
	echo "done."
}

# arg 1: the new package version
# arg 2: the old package version
post_upgrade() {
	post_install $1
}

# arg 1: the old package version
pre_remove() {
	echo -n "updating /etc/shells... "
	sed -i '/\/bin\/ash/ d' /etc/shells
	echo "done."
}

op=$1
shift

$op $*

# vim: ft=sh
