post_install()
{
	echo -n "updating fonts dir... "
	mkfontdir /usr/lib/X11/fonts/Speedo
	echo "done."
	echo -n "updating fonts cache... "
	fc-cache /usr/lib/X11/fonts/Speedo
	echo "done."
}

post_remove()
{
	echo -n "updating fonts dir... "
	mkfontdir /usr/lib/X11/fonts/Speedo
	echo "done."
	echo -n "updating fonts cache... "
	fc-cache /usr/lib/X11/fonts/Speedo
	echo "done."
}

op=$1
shift

$op $*

# vim: ft=sh
