post_install() {
	chkconfig --add rc.gpm
	systemctl enable gpm.service >/dev/null 2>&1
}

post_upgrade() {
	systemctl daemon-reload >/dev/null 2>&1
	if [ `vercmp $2 1.20.6-3` -lt 0 ] ; then
		if chkconfig rc.gpm; then
			post_install
		fi
	fi
}

pre_remove() {
	chkconfig --del rc.gpm
	systemctl --no-reload disable gpm.service >/dev/null 2>&1
	systemctl stop gpm.service >/dev/null 2>&1
}

post_remove() {
	systemctl daemon-reload >/dev/null 2>&1
}

op=$1
shift
$op $*
