post_install() {
	systemctl enable gpm.service >/dev/null 2>&1
}

post_upgrade() {
	systemctl daemon-reload >/dev/null 2>&1
	# this can be removed after Frugalware-1.6
	rm -f /etc/rc.d/rc?.d/???rc.gpm
}

pre_remove() {
	systemctl --no-reload disable gpm.service >/dev/null 2>&1
	systemctl stop gpm.service >/dev/null 2>&1
}

post_remove() {
	systemctl daemon-reload >/dev/null 2>&1
}

op=$1
shift
$op $*
