post_install() {
	cat << 'EOM'
==> Remember to enable extended attributes on the partitions you wish to index.
 -> This can be done by adding the user_xattr mount option in /etc/fstab.
 -> To activate it on a running system, run: mount -o remount <mount point>
 -> You must also build Beagle's index. This is automatically done daily, but
 -> it is recommended that you run /usr/libexec/beagle-crawl-system as a normal
 -> user now.
EOM
}

op=$1
shift
$op $*
