dictlst=/usr/lib/ooo-1.1/share/dict/ooo/dictionary.lst

post_install()
{
	echo "DICT pt BR pt_BR" >>$dictlst
	echo "DICT pt PT pt_PT" >>$dictlst
	echo "HYPH pt BR hyph_pt_BR" >>$dictlst
	echo "HYPH pt PT hyph_pt_PT" >>$dictlst
}

pre_remove()
{
	tempfile=`mktemp`
	cat $dictlst |grep -v "\(DICT pt BR pt_BR\|DICT pt PT pt_PT\|HYPH pt BR hyph_pt_BR\|HYPH pt PT hyph_pt_PT\)" >$tempfile
	cat $tempfile >$dictlst
	rm -f $tempfile
}

op=$1
shift
$op $*

# vim: ft=sh
