post_install() {
	# We need to ldconfig first, in case x's libs aren't
	# in ld.so.cache yet.
	/sbin/ldconfig -r .
	
	echo -n "updating pango modules... "
#	/usr/bin/pango-querymodules > /etc/pango/pango.modules
	/usr/bin/pango-querymodules --update-cache
	echo "done."
}

post_upgrade() {
	if [ -f /etc/pango/pango.modules ]; then
		rm /etc/pango/pango.modules
	fi
	post_install $1
}

pre_remove() {
#	rm /etc/pango/pango.modules
	/usr/bin/pango-querymodules --update-cache
}

op=$1
shift

$op $*
