dictlst=/usr/lib/ooo-1.1/share/dict/ooo/dictionary.lst

post_install()
{
	echo "DICT sv SE sv_SE" >>$dictlst
	echo "HYPH sv SE hyph_sv_SE" >>$dictlst
}

post_upgrade()
{
        pre_remove
        post_install
}

pre_remove()
{
	tempfile=`mktemp`
	cat $dictlst |grep -v "\(DICT sv SE sv_SE\|HYPH sv SE hyph_sv_SE\)" >$tempfile
	cat $tempfile >$dictlst
	rm -f $tempfile
}

op=$1
shift
$op $*

# vim: ft=sh
