dictlst=/usr/lib/ooo-1.1/share/dict/ooo/dictionary.lst

post_install()
{
	echo "DICT lt LT lt_LT" >>$dictlst
	echo "HYPH lt LT hyph_lt_LT" >>$dictlst
}


post_upgrade()
{
        pre_remove
        post_install
}
		
pre_remove()
{
	tempfile=`mktemp`
	cat $dictlst |grep -v "\(DICT lt LT lt_LT\|HYPH lt LT hyph_lt_LT\)" >$tempfile
	cat $tempfile >$dictlst
	rm -f $tempfile
}

op=$1
shift
$op $*

# vim: ft=sh
