# arg 1:  the new package version
post_install() {
  cd /usr/X11/lib/X11/icons/default
  cat index.theme|grep -v Inherits= >.tmp
  mv -f .tmp index.theme
  echo "Inherits=Silver" >>index.theme
}

# arg 1:  the new package version
# arg 2:  the old package version
post_upgrade() {
  /bin/true
}

# arg 1:  the old package version
pre_remove() {
  cd /usr/X11/lib/X11/icons/default
  cat index.theme|grep -v Inherits= >.tmp
  mv -f .tmp index.theme
  echo "Inherits=core" >>index.theme
}

# arg 1:  the old package version
post_remove() {
  /bin/true
}


op=$1
shift

$op $*
