post_install()
{
	systemctl enable syslog-ng.service >/dev/null 2>&1
}

pre_remove()
{
	systemctl --no-reload disable syslog-ng.service >/dev/null 2>&1
	systemctl stop syslog-ng.service >/dev/null 2>&1
}

post_remove()
{
	systemctl daemon-reload >/dev/null 2>&1
}

post_upgrade()
{
	systemctl daemon-reload >/dev/null 2>&1
	if [ `vercmp $2 3.2.4-1` -lt 0 ] ; then
		if chkconfig rc.syslog-ng; then
			post_install
		fi
	fi
}

op=$1
shift
$op $*
