warning()
{
	echo "Read the license at /usr/share/doc/fglrx/ATI_LICENSE.TXT ."
	echo "If you do not agree, remove this package."
}

post_install()
{
	depmod -a @_F_kernelmod_uname@
	echo "blacklist radeon" >> /etc/modprobe.d/blacklist.conf
	warning
}

post_upgrade()
{
	depmod -a @_F_kernelmod_uname@
	warning
}

post_remove()
{
	depmod -a @_F_kernelmod_uname@
	sed -i '/^blacklist radeon$/ d' /etc/modprobe.d/blacklist.conf
}

op=$1
shift
$op $*
