post_install()
{
	if [ -e /usr/sbin/chkconfig ] && [ -x /usr/sbin/chkconfig ]; then
		echo "START adding rc.system-tools-backends to boot"
		/usr/sbin/chkconfig --add rc.system-tools-backends
		echo "DONE $?"
	fi
}

post_upgrade()
{
	post_install $1
}

pre_remove()
{
	if [ -e /usr/sbin/chkconfig ] && [ -x /usr/sbin/chkconfig ]; then
		echo "START removing rc.system-tools-backends from boot"
		/usr/sbin/chkconfig --del rc.system-tools-backends
		echo "DONE $?"
	fi
}

op=$1
shift
$op $*

