post_install()
{
	cat << EOF
Do not use or load this firmware (the "Software") until you have carefully read
the terms and conditions in /usr/share/doc/ipw2200-`echo $1|sed 's/\(.*\)-.*/\1/'`/LICENSE.
By loading or using the Software, you agree to the terms of this Agreement.
If you do not wish to so agree, do not use the Software.
EOF
	/sbin/depmod -a
}

post_upgrade()
{
	post_remove
}

post_remove()
{
	/sbin/depmod -a
}

op=$1
shift
$op $*

# vim: ft=sh
