post_install()
{
	getent passwd syncpkgd >/dev/null || /usr/sbin/useradd -g 2 -u 12 syncpkgd
	if [ -e /etc/sudoers ]; then
		if ! grep -q syncpkgd /etc/sudoers; then
			echo "syncpkgd ALL=(ALL) NOPASSWD: /usr/bin/makepkg" >>/etc/sudoers
		fi
	fi
}

post_upgrade()
{
	post_install
}

pre_remove()
{
	userdel syncpkgd
	if [ -e /etc/sudoers ]; then
		sed -i '/syncpkgd ALL=(ALL) NOPASSWD: \/usr\/bin\/makepkg/d' /etc/sudoers
	fi
}

op=$1
shift

$op $*
