#!/bin/bash

# fake variable for fwmakepkg
CHROOT=1

. functions.sh
. /etc/makepkg.conf
. /usr/lib/frugalware/fwmakepkg

if [ "$1" == "--help" ]; then
	echo "missing source files"
	exit 1
fi

if [ "$1" == "--download" ]; then
	download="y"
	shift
fi
startdir=..

cd $startdir
for i in `find source -maxdepth 5 -name FrugalBuild`
do
	cd `dirname $i` || continue
	unset nobuild options archs
	. FrugalBuild || echo "errors parsing the FrugalBuild"
	if [ ! -z "$pkgname" -a ! "$nobuild" -a ! "`check_option NOBUILD`" ]; then
		for j in ${archs[@]}
		do
			export CARCH=$j
			unset source
			export startdir=`pwd`
			. FrugalBuild || echo "errors parsing the FrugalBuild for $j"
			for k in ${source[@]}
			do
				file=`strip_url $k`
				if [ ! -e "$file" ]; then
					echo "`dirname $i`: $file is missing"
					if [ ! -z "$download" ]; then
						echo "downloading $file..."
						$FTPAGENT $k
					fi
				fi
			done
		done
	fi
	cd - >/dev/null
done
