dictlst=/usr/lib/ooo-2.0/share/dict/ooo/dictionary.lst

post_install()
{
	echo "DICT hu HU hu_HU" >>$dictlst
	echo "HYPH hu HU hyph_hu" >>$dictlst
	echo "THES hu HU th_hu_HU" >>$dictlst
}

post_upgrade()
{
	pre_remove
	post_install
}

pre_remove()
{
	tempfile=`mktemp`
	cat $dictlst |grep -v "\(DICT hu HU hu_HU\|HYPH hu HU hyph_hu\|THES hu HU th_hu_HU\)" >$tempfile
	cat $tempfile >$dictlst
	rm -f $tempfile
}

op=$1
shift
$op $*

# vim: ft=sh
