#!/bin/bash

if [ "$1" ==  "--help" ]; then
	echo "packages larger than 100MB in the games-extra category (make them nobuild)"
	exit 1
fi

cd ..
for i in frugalware-*
do
	cd $i
	for j in *
	do
		# 100mb
		if [ `stat -c "%s" $j` -gt 104857600 ] && \
			pacman -Qi -p $j|grep -q '^Groups.*games-extra'; then
			echo $i/$j
		fi
	done
	cd ..
done
