#!/bin/bash

if [ "$1" ==  "--help" ]; then
        echo "packages with invalid /usr/etc path"
        exit 1
fi

find ../frugalware-* -type f -name "*.fpm" -print0 | xargs -0 -n 100 -P 16 -I{} \
	bash -c "pacman-g2 -Ql -p {} | grep -q usr/etc && echo {}"
