#!/bin/bash

if [ "$1" ==  "--help" ]; then
	echo "missing packages (missing != not synced, syncpkgd will fix the later ones)"
	exit 1
fi

tmp=`mktemp -d`

cd ..
for i in frugalware-*
do
	arch=${i#frugalware-}
	cd $i
	tar xf frugalware-current.fdb -C $tmp
	for j in `ls $tmp`
	do
		pkg=$j-$arch.fpm
		[ -f "$pkg" ] || echo "$i/$pkg is missing"
	done
	rm -rf $tmp
	mkdir -p $tmp
	cd ..
done

rm -rf tmp
