diff -Naur klearlook-0.9.9/Makefile.in klearlook-0.9.9-lol/Makefile.in
--- klearlook-0.9.9/Makefile.in	2006-04-25 08:13:46.000000000 +0200
+++ klearlook-0.9.9-lol/Makefile.in	2006-04-26 19:10:39.000000000 +0200
@@ -719,7 +719,7 @@
 uninstall: uninstall-recursive
 
 install-colorthemes:
-	$(install_sh_DATA) colorshemes/Klearlook.kcsrc $(kdecolorchemes)/Klearlook.kcsrc
+	$(install_sh_DATA) colorshemes/Klearlook.kcsrc $(DESTDIR)$(kdecolorchemes)/Klearlook.kcsrc
 
 install-am: all-am
 	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am
