# arg 1:  the new package version
post_install() {
  chkconfig --add rc.local
  chkconfig --add rc.reboot
  chkconfig --add rc.single
}

# arg 1:  the new package version
# arg 2:  the old package version
post_upgrade() {
  /bin/true
}

# arg 1:  the old package version
pre_remove() {
  chkconfig --del rc.local
  chkconfig --del rc.reboot
  chkconfig --del rc.single
}

# arg 1:  the old package version
post_remove() {
  /bin/true
}

op=$1
shift
$op $*
