# arg 1: the new package version
post_install() {
	if [ ! "`grep /usr/bin/tcsh etc/shells`" ]; then
		echo "updating /etc/shells... done."
		sed -i "s|/bin/bash|/bin/bash\n/usr/bin/tcsh|" etc/shells
	fi
	/bin/true
}

# arg 1: the new package version
# arg 2: the old package version
post_upgrade() {
	post_install $1
}

# arg 1: the old package version
pre_remove() {
	echo -ne "\nupdating /etc/shells... "
	sed -i "s|/usr/bin/tcsh||" etc/shells
	/bin/true
}

op=$1
shift

$op $*
