# arg 1: the new package version
post_install()
{
	if [ ! "`grep /usr/bin/tcsh etc/shells`" ]; then
		echo -n "updating /etc/shells... "
		sed -i "s|/bin/bash|/bin/bash\n/usr/bin/tcsh|" etc/shells
		echo "done."
	fi
}

# arg 1: the new package version
# arg 2: the old package version
post_upgrade()
{
	post_install $1
}

# arg 1: the old package version
pre_remove()
{
	echo -n "updating /etc/shells... "
	sed -i "s|/usr/bin/tcsh||" etc/shells
	echo "done."
}

op=$1
shift

$op $*

# vim: ft=sh
