post_install() {
        getent group pulse > /dev/null 2>&1 || /usr/sbin/groupadd pulse
        getent passwd pulse > /dev/null 2>&1 || /usr/sbin/useradd -c 'Pulseaudio System Instance' -u 631 -g pulse -d /run/pulse -s /sbin/nologin pulse
        passwd -l pulse > /dev/null
}

post_upgrade()
{
	post_install
}

post_remove()
{
        getent passwd pulse > /dev/null 2>&1 || /usr/sbin/userdel -r pulse
	getent group pulse > /dev/null 2>&1 || /usr/sbin/groupdel pulse
}


op=$1
shift
$op $*
