\input texinfo
@setfilename frugalware.info
@settitle Frugalware Linux Documentation
@documentencoding UTF-8

@copying
	Voici le manuel et la documentation officielle, écrits maintenus par 
	l'équipe de développeurs Frugalware.
	            
	Copyright @copyright{} 2003-2006 l'équipe de développeurs Frugalware.
         
	Ce document est distribué sous licence
	GNU Free Documentation License (GFDL).
@end copying

@node Top,	Premiers pas, Contenu, Top
@c node-name,     next,        previous,         up

@center Documentation pour Frugalware Linux 0.5

@menu
* Premiers pas::                   A propos, FAQ, historique, etc.
* Installer et configurer::        Installation de la distribution et configuration
                                   des services tels qu'impression, réseau etc..
* Developpement::                  Création de paquets, recompilation d'existants avec
                                   plus d'options que dans la distribution.
* Contenu::
* Top::
@end menu

@insertcopying

@c proper href: @uref{}
@c command sample: @samp{rm / -rf}
@c
@c
@c
@c the first big section, lead-in
@include frugalware-firststeps.texi

@c configuration
@include frugalware-installconfig.texi

@c developer docs, about recompiling, creating packages
@include frugalware-devel.texi

@node Contenu, Top, Developpement, Top
@unnumbered

@contents

@bye
