post_install() {
	export HOME="/root"
	firefox -register
	update-desktop-database -q > /dev/null 2>&1
}

post_upgrade() {
	post_install
}

post_remove() {
	pkgver=`echo $1|sed 's/\(.*\)-.*/\1/'`
	if [ -d /usr/lib/firefox-$pkgver ]; then
		rm -rf /usr/lib/firefox-$pkgver
	fi

	if [ -d /usr/lib/firefox ]; then
		rm -rf /usr/lib/firefox
	fi
	update-desktop-database -q > /dev/null 2>&1
}

op=$1
shift

$op $*

# vim: ft=sh
