post_install()
{
	systemctl daemon-reload >/dev/null 2>&1
}

post_upgrade()
{
	# can be removed after Frugalware-1.5
	rm -f /etc/rc.d/rc?.d/???rc.ajaxterm
	systemctl daemon-reload >/dev/null 2>&1
}

pre_remove()
{
	systemctl --no-reload disable ajaxterm.service >/dev/null 2>&1
	systemctl stop ajaxterm.service >/dev/null 2>&1
}

post_remove()
{
	systemctl daemon-reload >/dev/null 2>&1
}

op=$1
shift
$op $*
