\input texinfo
@setfilename frugalware.info
@settitle Dokumentacja Frugalware Linux

@copying
	To jest oryginalna dokumentacja Frugalware stworzona przez
	twórców systemu i przetłumaczona na język polski.
	            
	Copyright @copyright{} 2003-2006 The Frugalware Developer Team.
         
	This document is distributed under the
	GNU Free Documentation License (GFDL).
@end copying

@node Góra,	Pierwsze Kroki, Spis Treści, Góra
@c node-name,     dalej,        wstecz,         góra

@center Dokumentacja Frugalware Linux 0.5

@menu
* Pierwsze Kroki::            O systemie, FAQ, historia
* Instalacja i konfiguracja::  Instalacja dystrybucji i konfiguracja systemu
* Modyfikacje::            Tworzenie i rekompilacja pakietów.
* Spis Treści::
* Góra::
@end menu

@insertcopying

@c proper href: @uref{}
@c command sample: @samp{rm / -rf}
@c
@c
@c
@c the first big section, lead-in
@include frugalware-firststeps.texi

@c configuration
@include frugalware-installconfig.texi

@c developer docs, about recompiling, creating packages
@include frugalware-devel.texi

@node Spis Treści, Góra, Modyfikacje, Góra
@unnumbered

@contents

@bye
