dictlst=/usr/lib/ooo-1.1/share/dict/ooo/dictionary.lst

post_install()
{
	echo "DICT pl PL pl_PL" >>$dictlst
	echo "HYPH pl PL hyph_pl_PL" >>$dictlst
	echo "THES pl PL th_pl_PL" >>$dictlst
}

post_upgrade()
{
        pre_remove
        post_install
}

pre_remove()
{
	tempfile=`mktemp`
	cat $dictlst |grep -v "\(DICT pl PL pl_PL\|HYPH pl PL hyph_pl_PL\|THES pl PL th_pl_PL\)" >$tempfile
	cat $tempfile >$dictlst
	rm -f $tempfile
}

op=$1
shift
$op $*

# vim: ft=sh
