post_install()
{
	echo -n "updating rarian database..."
	if rarian-sk-update -q > /dev/null 2>&1 ; then
		echo " done."
	else
		echo " failed."
	fi
	systemctl enable NetworkManager.service >/dev/null 2>&1
	
}

post_upgrade()
{
	post_install $1
}


post_remove()
{
	echo -n "updating rarian database..."
	if rarian-sk-update -q > /dev/null 2>&1 ; then
		echo " done."
	else
		echo " failed."
	fi
	systemctl disable NetworkManager.service >/dev/null 2>&1
}

op=$1
shift

$op $*
