dictlst=/usr/lib/ooo-1.1/share/dict/ooo/dictionary.lst

post_install()
{
	echo "DICT es ES es_ES" >>$dictlst
	echo "DICT es MX es_MX" >>$dictlst
	echo "HYPH es ES hyph_es_ES" >>$dictlst
	echo "THES es ES th_es_ES" >>$dictlst
}

pre_remove()
{
	tempfile=`mktemp`
	cat $dictlst |grep -v "\(DICT es ES es_ES\|DICT es MX es_MX\|HYPH es ES hyph_es_ES\|THES es ES th_es_ES\)" >$tempfile
	cat $tempfile >$dictlst
	rm -f $tempfile
}

op=$1
shift
$op $*

# vim: ft=sh
