post_install() {
	/usr/sbin/groupadd -g 503 -f bitlbee
	/usr/sbin/useradd -g bitlbee -s /dev/null -d /dev/null -u 503 bitlbee
	/usr/bin/sed -e 's|/usr/sbin/swat.*swat|&\n6667 stream tcp nowait bitlbee /usr/sbin/tcpd /usr/sbin/bitlbee|' -i /etc/inetd.conf
}

post_remove() {
	/usr/sbin/userdel bitlbee
	/usr/bin/sed -e '/6667 stream tcp nowait bitlbee \/usr\/sbin\/tcpd \/usr\/sbin\/bitlbee/d' -i /etc/inetd.conf
}

op=$1
shift
$op $*
