post_install()
{
	echo -n "updating desktop database... "
	if update-desktop-database > /dev/null 2>&1 ; then
		echo "done."
	else
		echo "failed."
	fi
	echo -n "updating mime database... "
	if update-mime-database /usr/share/mime > /dev/null 2>&1 ; then
		echo "done."
	else
		echo "failed."
	fi
}

post_update()
{
	post_install
}

post_remove()
{
	post_install
}

op=$1
shift

$op $*

# vim: ft=sh
