post_install()
{
	GCONF_CONFIG_SOURCE=`gconftool-2 --get-default-source` \
	gconftool-2 --makefile-install-rule /etc/gconf/schemas/liferea.schemas \
	> /dev/null 2>&1
	kill -HUP `pidof /usr/libexec/gconfd-2` > /dev/null 2>&1
}

pre_remove()
{
	GCONF_CONFIG_SOURCE=`gconftool-2 --get-default-source` \
	gconftool-2 --makefile-uninstall-rule \
	/etc/gconf/schemas/liferea.schemas > /dev/null 2>&1
}

op=$1
shift

$op $*

# vim: ft=sh
