post_install()
{
	if ! grep -q '^clamav:' /etc/group ; then
		groupadd -g 26 clamav
	fi
	if ! grep -q '^clamav:' /etc/passwd ; then
                useradd -u 26 -g 26 -s /bin/false -c "Clam AntiVirus" -d /var/lib/clamav clamav
	fi
}

pre_remove()
{
	userdel -r clamav >/dev/null 2>&1
	groupdel clamav >/dev/null 2>&1
	rm -fr /var/lib/clamav 2>&1
}

pre_upgrade() 
{
	if [ `vercmp $2 0.88.7-2` -lt 0 ] ; then
		chkconfig --del freshclam
	fi
}

op=$1
shift

$op $*
