post_install()
{
	echo -n "updating fonts scale... "
	mkfontscale /usr/lib/X11/fonts/100dpi
	echo "done."
	echo -n "updating fonts dir... "
	mkfontdir /usr/lib/X11/fonts/100dpi
	echo "done."
}

post_remove()
{
	echo -n "updating fonts scale... "
	mkfontscale /usr/lib/X11/fonts/100dpi
	echo "done."
	echo -n "updating fonts dir... "
	mkfontdir /usr/lib/X11/fonts/100dpi
	echo "done."
}

op=$1
shift

$op $*

# vim: ft=sh
