#! /bin/bash

BASENAME=/home/ftp/pub/frugalware/frugalware-current
WHICH=m

# Ugly but needed for some FrubalBuilds
error(){
	echo "$1" > /dev/null
}
Fdie(){
	echo "$1" > /dev/null
}
Finclude(){
	return 0;
}

chk_status() # $1 = path to a FrugalBuild script, $2 = repo
{
	nobuild=0
	source $1
	if (( $nobuild == 1 )) ; then exit 0 ; fi
	pkg="${pkgname}-${pkgver}-${pkgrel}"
	file32="/$2/frugalware-i686/${pkg}-i686.fpm"
	file64="/$2/frugalware-x86_64/${pkg}-x86_64.fpm"
	if echo ${archs[*]} | grep -q i686 ; then
		output=$(repoman ls ${file32} 2> /dev/null)
		if [[ "${output}" != "${BASENAME}/${file32}" ]] ; then
			status32=31
		else
			status32=32
		fi
	else
		status32=33
	fi
	if echo ${archs[*]} | grep -q x86_64 ; then
		output=$(repoman ls ${file64} 2> /dev/null)
		if [[ "${output}" != "${BASENAME}/${file64}" ]] ; then
			status64=31
		else
			status64=32
		fi
	else
		status64=33
	fi
	group=$(basename $(dirname $(dirname $1)))
	if [[ "$2" == "extra" ]] ; then
		repo=extra/${group}
	else
		repo=${group}
	fi
	if [[ "${WHICH}" == "a" ]] ; then
		msg ${pkg} ${repo} ${status32} ${status64}
	elif [[ "${WHICH}" == "d" ]] && (( ${status32} != ${status64} )) ; then
		msg ${pkg} ${repo} ${status32} ${status64}
	elif [[ "${WHICH}" == "m" ]] && (( ${status32} == 31 )) || (( ${status64} == 31 )) ; then
		msg ${pkg} ${repo} ${status32} ${status64}
	fi
}

help_msg()
{
	echo "checkpkgs [-a] [-d] [-m]"
	echo
	echo "     -a    Print out all packages"
	echo -e "     -d    Print packages that are not in i686 \033[01mand\033[0m x86_64 or"
	echo "           not found."
	echo "     -m    Print only packages that are not found."
	echo
}

msg() # $1 = package name, $2 = repo, $3 = status i686, $4 = status x86_64
{
	printf "\033[01m%-35s \033[0m%-25s \033[01;%smi686\t\033[01;%smx86_64\033[0m\n" \
	$1 $2 $3 $4
}

case $1 in
	--all|-a)     WHICH=a ;;
	--diff|-d)    WHICH=d ;;
	--missing|-m) WHICH=m ;;
	--help|-h)    help_msg && exit 0 ;;
	--*|-*)       help_msg && exit 1 ;;
esac

cd ../source || exit 1

for pkg in $(find . -name FrugalBuild | sort) ; do
	chk_status ${pkg}
done

cd ../extra/source || exit 1

for pkg in $(find . -name FrugalBuild | sort) ; do
	chk_status ${pkg} extra
done

exit 0
