#!/bin/sh

if [ -z "$1" -o -z "$2" ]; then
	echo "Usage: $0 <extended regular expression> <FPMs>"
	exit 1
fi

ERE="$1"
shift 1

DIR="$(mktemp -td)"
cd $DIR

for i in $@; do
	tar -xf "$i"
	IFS=$'\n'
	for j in $(find -type f); do
		if file "$j" | grep -q 'ELF'; then
			if readelf -d "$j" | grep -qE "$ERE"; then
				echo "$i -> $j is a match"
			fi
		fi
	done
	IFS=$' '
	rm -rf * .* 2> /dev/null
done

rm -rf $DIR
