#!/bin/bash

# fix permissions of uploaded files

cd ..
file=`mktemp`
find * -perm 755 ! -type d >$file
find * -type d |xargs chmod 755
find * ! -type d ! -type l |xargs chmod 644
cat $file |xargs chmod +x
rm $file

chown -R vmiklos.users *
