#!/bin/bash

version=`date +%Y%m%d`
base=('base' 'apps' 'lib' 'multimedia' 'network' 'devel')
x11=('x11' 'xlib' 'xapps' 'xfce4' 'gnome' 'kde')
archs=('i686' 'x86_64')
tree=-current
arch=i686
dbpath=`mktemp -d`
target=../frugalware$target-iso/
cd ..

echo -n "preparing pkgdb... "
mkdir $dbpath/local $dbpath/frugalware$tree $dbpath/extra$tree
tar xzf frugalware-$arch/frugalware$tree.fdb -C $dbpath/frugalware$tree
tar xzf extra/frugalware-$arch/extra$tree.fdb -C $dbpath/extra$tree
echo "done."

# generate exclusion list for cd1 and cd2
baselst=`for i in $(pacman -b $dbpath -Sg ${base[@]} |grep -v '^\w'); do ls frugalware-i686/$i*|grep "/$i-[^-]*-[^-]*-$arch.fpm$"|sed 's|\(.*\)| -x ./\1|'; done`
x11lst=`for i in $(pacman -b $dbpath -Sg ${x11[@]} |grep -v '^\w'); do ls frugalware-i686/$i*|grep "/$i-[^-]*-[^-]*-$arch.fpm$"|sed 's|\(.*\)| -x ./\1|'; done`


# exlustion other arch's pkgs
for i in ${archs[@]}
do
	[ "$i" != "$arch" ] && binex="$binex -x ./frugalware-$i -x ./extra/frugalware-$i -x ./boot/initrd-$i.img.gz -x ./boot/vmlinuz-*-$i"
done

# use this to exlude the given arch's packages, so keep only kernel & initrd
for i in ${archs[@]}
do
	if [ "$i" != "$arch" ]; then
		binexall="$binexall -x ./frugalware-$i -x ./extra/frugalware-$i -x ./boot/initrd-$i.img.gz -x ./boot/vmlinuz-*-$i"
	else
		binexall="$binexall -x ./frugalware-$i -x ./extra/frugalware-$i"
	fi
done

sed -i "s/i686/$arch/g" boot/grub/menu.lst

for i in $*
do
case $i in
net)
# CD0: netinstall
mkisofs -o frugalware-$version-$arch-net.iso \
	-R -J -V "Frugalware Install" \
	-A "Frugalware Install Network Install" \
	-x ./_darcs \
	-x ./source \
	$binexall \
	-x ./extra \
	-hide-rr-moved \
	-b boot/grub/stage2_eltorito \
	-v -d -N -no-emul-boot -boot-load-size 4 -boot-info-table . || exit 1
mv frugalware-$version-$arch-net.iso $target
;;

cd1)
# CD1: base system
mkisofs -o frugalware-$version-$arch-cd1.iso \
	-R -J -V "Frugalware Install" \
	-A "Frugalware Install CD 1" \
	-x ./_darcs \
	-x ./source \
	$binex \
	-x ./extra \
	$x11lst \
	-hide-rr-moved \
	-b boot/grub/stage2_eltorito \
	-v -d -N -no-emul-boot -boot-load-size 4 -boot-info-table . || exit 1
mv frugalware-$version-$arch-cd1.iso $target
;;

cd2)
# CD2: x11 system
mkisofs -o frugalware-$version-$arch-cd2.iso \
	-R -J -V "Frugalware Install" \
	-A "Frugalware Install CD 2" \
	-x ./_darcs \
	-x ./source \
	$binex \
	-x ./extra \
	$baselst \
	-hide-rr-moved \
	-b boot/grub/stage2_eltorito \
	-v -d -N -no-emul-boot -boot-load-size 4 -boot-info-table . || exit 1
mv frugalware-$version-$arch-cd2.iso $target
;;

cd3)
# CD3: extra repo
mkisofs -o frugalware-$version-$arch-cd3.iso \
	-R -J -V "Frugalware Install" \
	-A "Frugalware Install CD 3" \
	-x ./_darcs \
	-x ./frugalware-$arch \
	-x ./source \
	-x ./extra/source \
	$binex \
	-hide-rr-moved \
	-b boot/grub/stage2_eltorito \
	-v -d -N -no-emul-boot -boot-load-size 4 -boot-info-table . || exit 1
mv frugalware-$version-$arch-cd3.iso $target
;;

dvd)
# DVD: full tree
mkisofs -o frugalware-$version-$arch-dvd.iso \
	-R -J -V "Frugalware Install" \
	-A "Frugalware Install DVD" \
	-x ./_darcs \
	-x ./source \
	-x ./extra/source \
	$binex \
	-hide-rr-moved \
	-b boot/grub/stage2_eltorito \
	-v -d -N -no-emul-boot -boot-load-size 4 -boot-info-table . || exit 1
mv frugalware-$version-$arch-dvd.iso $target
;;
esac
done

sed -i "s/$arch/i686/g" boot/grub/menu.lst
rm -rf $dbpath
