#!/bin/bash

[ -z "$arch" ] && arch=`arch`
tree=-current
dbpath=`mktemp -d`

cd `dirname $0`/..

echo -n "preparing pkgdb... "
mkdir $dbpath/local $dbpath/frugalware$tree $dbpath/extra$tree
tar xzf frugalware-$arch/frugalware$tree.fdb -C $dbpath/frugalware$tree
tar xzf extra/frugalware-$arch/extra$tree.fdb -C $dbpath/extra$tree
echo "done."

echo -n "generating packages list... "
pacman -b $dbpath -Sl >Packages-$arch.lst
echo "done."

rm -rf $dbpath
