post_install()
{
	systemctl enable acpid.service >/dev/null 2>&1
}

post_upgrade()
{
	systemctl daemon-reload >/dev/null 2>&1
	if [ `vercmp $2 2.0.12-1` -lt 0 ] ; then
		chkconfig --del rc.acpid
	fi
}

pre_remove()
{
	systemctl --no-reload disable acpid.service >/dev/null 2>&1
	systemctl stop acpid.service >/dev/null 2>&1
}

post_remove()
{
	systemctl daemon-reload >/dev/null 2>&1
}

op=$1
shift
$op $*
