post_install()
{
	chkconfig --add rc.acpid
	systemctl enable acpid.service >/dev/null 2>&1
}

post_upgrade()
{
	systemctl daemon-reload >/dev/null 2>&1
	if [ `vercmp $2 2.0.7-1` -lt 0 ] ; then
		if chkconfig rc.acpid; then
			post_install
		fi
	fi
}

pre_remove()
{
	chkconfig --del rc.acpid
	systemctl --no-reload disable acpid.service >/dev/null 2>&1
	systemctl stop acpid.service >/dev/null 2>&1
}

post_remove()
{
	systemctl daemon-reload >/dev/null 2>&1
}

op=$1
shift
$op $*
