= Artwork requirements

== Introduction

This document details the requirements that must be met by all artwork
if it is to be accepted into the official Frugalware gallery.

== The rules

* All artwork must be licensed under the Free Art License 1.3
  (link:http://artlibre.org/licence/lal/en/[full details]).

* Where the Frugalware logo appears, only the officially approved logo
  may be used. Refer
  link:http://frugalware.org/images/logo-new-big.png[here] for the logo.

NOTE: There is a newer SVG version available
http://frugalware.org/~devil505/artwork/[here].

* Artwork must be submitted in either SVG or XCF (The Gimp) format as
  this allows for derivative works to be made without affecting the impact
  of the original artwork. Examples of derivative works include wallpapers
  in various sizes and height/width ratios, and/or KDM/GDM/SLiM themes.
  To suit the varying sizes and ratios of monitors, any wallpaper must be
  a minimum 1600 pixels wide and provided in both 4:3 and 16:9 ratios.

* All artwork must be submitted together with any associated source
  files - i.e. files which are required by the graphics editor used by
  the entrant to reproduce and/or edit the artwork.

* Only FLOSS software may be used to create the wallpaper.

* Neither the release's version number, nor code-name are to appear in
  artwork, or there should be a version without them for later use when
  a given release is no longer supported.
