= How to contribute

If you appreciate our work, please consider contributing. Below are examples
of ways in which you can help the Frugalware project. If you want to help in
a way that's not described here, please tell us of your idea in an email to
the Frugalware users' mailing list, or add an entry to the Frugalware forums.


== Donations of money

Donations of money are welcome and will be used to cover costs such as domain
name registration, hosting costs (hardware, bandwidth etc). If you want to
donate, please use the "Donation" link on the Frugalware home page.

== Translation

Comprehensive, multi-lingual documentation is very important to us because we
want Frugalware to be available to as many people as possible. If you have the
required linguistic knowledge, you could help translate various pieces of work.
 These include our own applications, documentation, web site etc.

== Application packaging

In the http://bugs.frugalware.org[Bug Tracking System], are requests for
packages, from Frugalware's users. The process of making packages is well
documented in the http://frugalware.org/docs/stable/index-devel
[Frugalware Developer Documentation], and with some GNU/Linux experience, you
could contribute in that way. Existing package maintainers are always available
to help you, especially if you're new to packaging.

== Developing

Frugalware has several of its own applications, including:
* An ncurses installer;
* A GUI installer (fwife);
* A GUI package management tool (gfpm);
* A command-line package manager (pacman-g2);
* A GUI runlevel manager (gservice).

Help in further developing and enhancing these applications is welcome.

== Donating hardware

By sending us some wanted hardware (see http://frugalware.org/donations[donations]),
you can make testing packages easier, or speed up the package creation
process within a specific architecture.

== Artwork

We usually update our artwork (background images, grub splash, desktop manager
themes, window manager splashes and so on) for each release. If you are skilled
in this area, you're welcome to join the artwork team.

== Support

If you have time and knowledge, monitor the forums, read the mailing list
posts, hang around on IRC and try to answer peoples' questions.

== Find bugs

If you find bugs, you can help by submitting well-written bug reports, see the
Reporting Bugs section for more info.
