= The hotplug subsystem

== udev

The /dev directory under Frugalware is a ramdisk. Every device node is
created automatically during the system boot by the hotplug subsystem,
more specifically, by udev. It means there won't be unnecessary device
nodes in /dev, but it also means that if you create a device node manually,
it will exist only until the next shutdown/reboot.

If you want to force Frugalware to create a device node "manually" during each
boot, you must create a device file under `/lib/udev/devices`: it will be
copied on each boot automatically.

The udev needs sysfs, so it will only work with the 2.6.x kernel series.
Do not try to run udev on Frugalware with kernel series 2.4.x.

== Pen/Thumbdrives

Pendrives (also known as thumbdrives, or USB keys) are well-supported
through the hotplug scripts and udev. If you insert a pendrive into the
USB slot, udev will create a device node for it in /dev. Most pendrives
contain only one partition and their filesystem is vfat. In most cases,
the pendrive will behave like a SCSI disc. It means, you can find the
pendrive under /dev/sda and its first partition under /dev/sda1.
Adding the following line to /etc/fstab:

`/dev/sda1 /media/pendrive auto defaults,noauto,user 0 0`

will allow users to mount their pendrive if the device node
exists (if the device is inserted into the slot).

If you use KDE, Gnome or XFCE4 they will handle automatic mounting of
such devices. You should not edit /etc/fstab as automounting will not
work for you.
For blackbox, fluxbox, englightenment, e17  and other smaller window
manager users there is `ivman` for automounting, but it may not work as
well as in KDE, Gnome, XFCE4.
See also the automounting part of the documentation.

== Digital cameras

Typically, there are two types of digital cameras. Some of them support
both access methods, others use only one of them. First, most of the
cameras can be treated as a pendrive (USB Mass Storage device), you can
mount them and copy the pictures from them easily.

Other cameras support the Picture Transfer Protocol (PTP). You can
grab the pictures from them (and do lots of other actions) with `gphoto2`,
if your model is supported. (If it's not available on your system, a
simple `su -c \'pacman-g2 -S gphoto2\'` will install it onto your system.)

== Automounting: D-BUS, HAL and Ivman; Gnome and KDE

D-BUS is a simple IPC (inter-process communication) library based on messages.
HAL is a hardware abstraction layer which uses D-BUS. Ivman is based on HAL
and uses pmount ("policy mount"), which is a wrapper around the standard
mount program which permits normal users to mount removable devices
without an existing '/etc/fstab' entry.

Ivman is a daemon to automount CD-ROMs and DVDs when inserted in a drive,
or play audio CDs or video DVDs automatically. It is 100% userspace,
so it is a safe replacement for submount.

If you want to change the default settings, all config files are
located in /etc/ivman. They are plain XML files, just read them,
everything is quite self-explanatory.

Automounting also happens with KDE and Gnome, but their respective VFS
implementation does that, not ivman. Ivman is useful for other windowing systems
where is no support for such a feature.
