= Introduction

Before you start to read this document, you should know some important things
about how to read it.

== Things that you should really read

First there are some part of this document that you should really read, to
understand how Frugalware works and how to administer it.

.Important references to read:
* This introduction ;)
* How to use pacman-g2.
* How to manage services.

== Running console commands

Throughout this document, there is boxed text which shows you console output.
These are important and require quite some attention since most of the time
you are expected to run them and get the same output.

--------------
$ echo foo bar
foo bar
--------------

This is how a console log look. Let's look at its details so you understand
what it means.

The `echo foo bar` part is what you should type and it's the command. The
following line `foo bar` is the output of the previous command.

<<<>>>

You may wonder what differentiates the command from the output. You see that in
front of the command there is a `$`. This indicates that it's a command line,
but there is more meaning in this symbol. This symbol can change depending
on the user privileges required to run the command.

.Here is the list of the common prefix for the console commands:
* `$` indicates that any user can run the command. Most of the time it means
you have to run it with your own user account.

* `user$` indicates that the specified user's privileges are required to run
this command. Usually this is necessary for security reasons.
+
You can get an interactive shell for this user, replacing 'user' with the
desired user name, by issuing:
+
-----------
$ su - user
-----------

* `#` indicates that the `root` user's privileges are required to run this
command. Usually this is required to manage the system configuration.
+
You can get an interactive shell for 'root' running:
+
------
$ su -
------
