= KDE Bump HOWTO


== KDE4

You *MUST* follow this HOWTO when bumping KDE4 to a new version (even a minor version).

First, update KDE4 version (_F_kde_ver) in source/include/kde-version.sh.
Commit this (git commit kde.sh).
From kde-4.7.0 we store all the sha1sums in source/include/kde-version.sh so don't
forget to update that as well (you can use http://ftp.frugalware.org/pub/other/people/melko/kdesha.sh[this]
to fetch the sha1sums).

Next, packages must be compiled in the order listed below (if you find a
change that needs to be made to this list, poke the kde m8r).
You can generally find the sha1sums in the kde website (somewhere like http://kde.org/info/KdeVersion.php).
If it is a major bump (i.e. 4.6 to 4.7) it is wise to check the updated build
instructions on the Kde website, and work in a kde testing repo first.


'KDE4 compile order'

- kdelibs (1)
- kdepimlibs (1)
* kfilemetadata
* baloo
* baloo-widgets
* nepomuk-core
* nepomuk-widgets
* kactivities
- kdebase (1)
- kdebase-runtime (1)
- kde-base-artwork
- kdebase-workspace (1)

- konsole
- kdebase-workspace-wallpapers (-extra)
- svgpart (-extra)

- kdenetwork (virtual package)
* kdenetwork-filesharing
* kdenetwork-strigi-analyzers
* zeroconf-ioslave
* kget
* kopete
* kppp
* krdc
* krfb

- kdegraphics (-extra) (virtual package)
* kruler
* kolourpaint
* libkipi
* libkexiv2
* libkdcraw
* libksane
* mobipocket
* gwenview
* kcolorchooser
* kamera
* okular
* ksaneplugin
* kdegraphics-thumbnailers
* kdegraphics-strigi-analyzer
* kgamma
* ksnapshot

- libkcddb
- libkcompactdisc
- kdemultimedia

- libkomparediff2 (-extra)
- kdesdk (-extra)
- kdewebdev (-extra)

* analitza (-extra)
* libkdeedu (-extra)
* kqtquickcharts (-extra)
- kdeedu (-extra)

* pykde4 (-extra)
- kate (-extra)
- kdebindings (-extra) (virtual package) (2)
* smokegen
* smokeqt
* smokekde
* perlqt
* perlkde
* qtruby
* korundum
* kross-interpreters
* qyoto
* kimono

- kdeutils

- kdeadmin (-extra)
- kdeplasma-addons (-extra)

- kdeaccessibility (-extra)

- kdeartwork (-extra)

- kdetoys (-extra)
* amor
* kteatime
* ktux

- libkdegames (-extra)
- libkmahjongg (-extra)
* kdegames (-extra)

- kdepim-runtime
- kdepim (-extra)

- kde-l10n (3)
- oxygen-icons (4)

(1) = these 5 packages *MUST* be built first, and in *THIS* order.

(-extra) = kde-extra packages. Some are needed as makedepends for other packages.

(2) = packages split from kdebinding must be built with *THIS* order.

(3) kde-l10n is usually built last.

(4) oxygen-icons can be updated at anytime.


== KDE5


KDE5 is splitted into Frameworks (KF5), Plasma and applications.
Up to now only KF5 has been packaged, plasma is next.

=== KF5

As for kde4, update frameworks version in source/include/kde-version.sh (_F_kdever_frameworks).
Sha1sums are stored in the same file so don't forget to update them as well.
Packages must be compiled in the order listed below (if you find a change that needs to be
made to this list, poke the kde m8r).
You can generally find the sha1sums in the kde website (somewhere like http://kde.org/info/kde-frameworks-KF5Version.php).


'KF5 compile order'

 - extra-cmake-modules
 - attica-qt5
 - networkmanager-qt
 - kitemmodels
 - kitemviews
 - kplotting
 - threadweaver
 - kcodecs
 - kguiaddons
 - kidletime
 - kwidgetsaddons
 - sonnet
 - kconfig
 - kwindowsystem
 - solid
 - kcoreaddons
 - kcrash
 - kdbusaddons
 - ki18n
 - kglobalaccel
 - karchive
 - kdoctools
 - kjs
 - kimageformats
 - kauth
 - kjobwidgets
 - kcompletion
 - kdnssd
 - kconfigwidgets
 - kservice
 - kiconthemes
 - knotifications
 - kwallet5
 - kpty
 - kpackage
 - kemoticons
 - kdesu
 - ktextwidgets
 - kxmlgui
 - kbookmarks
 - kcmutils
 - kio
 - kparts
 - kdewebkit
 - kdesignerplugin
 - knewstuff
 - kdeclarative
 - kpeople
 - kxmlrpcclient
 - kinit
 - kded
 - knotifyconfig
 - kunitconversion
 - kjsembed
 - kross
 - kmediaplayer
 - ktexteditor
 - kapidox
 - frameworkintegration
 - kdelibs4support
 - khtml
 - kactivities5
 - plasma-framework
 - krunner5
