= Mailing List Rules

== Introduction

The purpose of this document is to define rules that help the communication on
the mailing lists of Frugalware Linux.

== Mailing Lists

.There are 3 read-only lists
* frugalware-announce for general announcements (low traffic)
* frugalware-security for Frugalware Security Advisories
* frugalware-bugs for newly opened tasks in the Bug Tracking System (This may
  be extended in future, currently you must use the web interface to comment a
  task.)

.There are 3 lists for developers
* frugalware-devel for general development questions. Every developer is
  supposed to read this list. It has a moderate traffic. (Usually only a few
  mails / day.)
* frugalware-git for Git commits. This is a high traffic list. Every developer
  is supposed to subscribe to this list, but feel free to set 'Mail delivery'
  to 'Disabled' if you don't want to receive mails. (This is required as only
  subscribed users can post to prevent spam.)
* frugalware-darcs for Darcs patches. No longer used, but we keep this list as
  the archive is useful sometimes.

.There are 3 lists for users
* frugalware-forums is a bidirectional gateway between the users of the
  Frugalware Forums
  (link:http://forums.frugalware.org/index.php?t=thread&frm_id=34[this forum])
  and people who read the mailing lists only. The primary benefit is that not
  all developers read the Forums, but mailing lists.
* frugalware-users is for general user questions. It seems the Forums are very
  popular, but we still provide a mailing list for user questions.
* frugalware-users-hu is for Hungarian user questions.

If not mentioned, then the language of the lists are English. Please use the
appropriate language. If you know of other non-English mailing lists, please
tell us, then we can include them here.

You can subscribe to our mailing lists
link:http://frugalware.org/mailman/listinfo[here]. Also you can unsubscribe or
edit your options there.

== Frugalware developers

Developers are supposed to read the `-devel` and `-users` mailing lists, and
supposed to be subscribed to the `-git` list.

== Off-list discussion

We don't set a `Reply-to:` header on our mailing lists. This is intentional. If
you don't understand why this is a good decision, first please read
link:http://www.unicom.com/pw/reply-to-harmful.html[this document].

In practice if this is a new situation for you, then use your mail client's
'list-reply' function, as the 'reply' function will send the mail off-list
which is not something you want in most cases.

Also please do not use the 'group-reply' function if possible. Users must
subscribe before they post, so you can be sure they are in the mailing list.

(This is different to some other projects' rules. Some projects require you to
use 'group-reply' all the time, please do not do so on our lists.)

== Top posting and HTML messages

Please do not link:http://www.idallen.com/topposting.html[top post] on our
lists. Also please try to avoid HTML messages, many developers use a console
mail client to read mails and reading such messages is always problematic.

== Archives

We have our own archive of our mailing lists
link:http://frugalware.org/pipermail/[here]. Gmane also provides
link:http://news.gmane.org/?prefix=gmane.linux.frugalware[searchable archives].
