= Basic configuration

== Introduction

After the installation of the packages, Frugalware setup will configure your
new Frugalware system. If you installed the packages manually, then you'll have
to perform those configuration steps manually.

NOTE: If any problem occurs, there is a debug console on `tty4`, you can see
that by pressing `Alt-F4`. You can switch back by hitting `Alt-F1`.

== GRUB

The first step is to install GRUB onto your hard disk. There are four options
here: installing to the MBR, the root partition, a floppy or simply skipping.
Installing to the MBR is the good choice if you want Frugalware to manage your
computer's booting.  The root is a good idea if you want to install GRUB into
your root partition.  In this case, GRUB will not modify your existing boot
manager. Floppy is a good idea for example if you don't have any boot manager
installed, but you want to leave your MBR unmodified.

== Kernel modules

After the installation of GRUB, the installer will configure your kernel
modules. This means that an information dialog appears, but nothing more.

== Accounts and passwords

After module configuration, you should change the root password. This is very
important as there is no default password. If you skip this step, anybody will
be able to login as root.

After this step, you can create a regular (also known as non-root) user.
It's highly recommended to create one, and log in as a regular user.
If a command should be run as root, you should use su or sudo under console,
and `gksu` or `kdesu` under X.

== Network

After this, setup will configure your network settings. Setup simply runs the
netconfig utility, which is described in the Networking section.

== Timezone

If network installation is done, we should configure the system's time.  This
means two actions. First, you should decide if the hardware (BIOS) clock is set
to Coordinated Universal Time (UTC). If yes, select yes here.  If the hardware
clock is set to the current local time (this is how most PCs are set up), say
no here. If you are not sure what is this, you should answer no here.

== Mouse

The next step is to configure your mouse. The configuration will take effect on
the console mouse services (gpm) and on the X server.  The setting is done by
xconfig later.

== Graphical interface

If you have installed an X server (by default xorg), the setup will run
xconfig. For more information on xconfig, see the section Graphical interface
(X11).
