= Graphical interface (X11)

== Configuring your graphics card

If you install X, a /etc/X11/xorg.conf.d directory will be created for
you, containing XOrg configuration fragment files. In most cases the
default configuration will be enough for you, but you can place your own
fragments there if you want to manually fine-tune some of the settings.

A common problem is to use a keyboard layout different to the default of
the locale, for example you have a non-English locale, thus the default
keyboard layout isn't English, either, but you want to have such one. In
that case you need to edit the evdev configuration:

----
# vi /etc/X11/xorg.conf.d/10-evdev.conf
----

and change the `xkb_layout` option there to `us`, for example.

== 3D acceleration, binary drivers

If there is built-in 3d acceleration support for your card in X, UDev
will detect the necessary drivers and X will enable support for them.

If you have an NVIDIA card, you probably need the manufacturer's
binary drivers. Obtaining the NVIDIA binary driver is fairly simple:

----------------------
# pacman-g2 -Sy nvidia
----------------------

== Allow root login in KDM/GDM

By default, no root login is permitted on the GUI, the recommended way of
running graphical programs as root is to use gksu or kdesu.

To enable it anyway, the following lines should be edited:

For KDM ('/etc/kde/config/kdm/kdmrc')

'AllowRootLogin=false'

modify to

'AllowRootLogin=true'

For GDM ('/etc/gdm/gdm.conf')

'AllowRoot=false'

modify to

'AllowRoot=true'
