dictlst=/usr/lib/ooo-1.1/share/dict/ooo/dictionary.lst

post_install()
{
	echo "DICT cs CZ cs_CZ" >>$dictlst
	echo "HYPH cs CZ hyph_cs_CZ" >>$dictlst
	echo "THES cs CZ th_cs_CZ" >>$dictlst
}

pre_remove()
{
	tempfile=`mktemp`
	cat $dictlst |grep -v "\(DICT cs CZ cs_CZ\|HYPH cs CZ hyph_cs_CZ\|THES cs CZ th_cs_CZ\)" >$tempfile
	cat $tempfile >$dictlst
	rm -f $tempfile
}

op=$1
shift
$op $*

# vim: ft=sh
