post_install() {
	echo "updating the filename database..."
	mktexlsr
	echo " done."
        echo "updating the fontmap files with updmap..."
	updmap-sys --quiet --nohash --syncwithtrees
        echo " done."
	echo "creating all formats..."
	fmtutil-sys --all 1>/dev/null
	texlinks -f /usr/share/texmf/web2c/fmtutil.cnf /usr/bin/
	echo " done."
}

pre_upgrade() {
	texlinks -u
}

post_upgrade() {
	post_install
}

pre_remove() {
	texlinks -u
}

op=$1
shift

$op $*
