post_install()
{
    update-desktop-database
    echo -n "updating scrollkeeper catalouge..."
    scrollkeeper-update -p /var/lib/scrollkeeper > /dev/null 2>&1
    echo "done."
}

post_upgrade()
{
    post_install $1
}

post_remove()
{
    update-desktop-database
    echo -n "updating scrollkeeper catalouge..."
    scrollkeeper-update -p /var/lib/scrollkeeper > /dev/null 2>&1
    echo "done."
}

op=$1
shift

$op $*

# vim: ft=sh
