post_install()
{
	echo -n "Updating desktop database..."
	if update-desktop-database > /dev/null 2>&1 ; then
		echo "done."
	else
		echo "failed."
	fi
	echo -n "updating scrollkeeper catalouge..."
	if scrollkeeper-update -p /var/lib/scrollkeeper > /dev/null 2>&1 ; then
		echo "done."
	else
		echo "failed."
	fi
}

post_upgrade()
{
	post_install
}

post_remove()
{
	post_install
}

op=$1
shift

$op $*

# vim: ft=sh
