post_install()
{
	[ -e /usr/lib/xorg-libGL.so.1.2 ] || cp /usr/lib/{,xorg-}libGL.so.1.2
	mv /usr/lib/libGL.so.1.2{.ati,}
	echo 'You have successfully installed the ATi proprietary driver!'
	echo 'To configure your xserver please run aticonfig!'
	echo 'Before using X please restart your computer!'
}

post_upgrade()
{
	post_install $1
}

pre_remove()
{
	mv /usr/lib/{xorg-,}libGL.so.1.2
}

op=$1
shift
$op $*

# vim: ft=sh
